# Generated by Django 5.2 on 2025-05-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_businessprofile_authorized_users_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
