# Generated by Django 5.2 on 2025-05-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_businessprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS myapp_userprofile (
                id SERIAL PRIMARY KEY,
                profile_picture VARCHAR(100) NULL,
                user_id INTEGER UNIQUE REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
            );
            CREATE INDEX IF NOT EXISTS myapp_userprofile_user_id_idx ON myapp_userprofile(user_id);
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS myapp_userprofile;
            """
        ),
    ]
