# Generated by Django 5.2 on 2025-05-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_businessprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
