# Generated by Django 5.2 on 2025-05-16 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_businessprofile_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, related_name='authorized_businesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
